version: "3"
services:
  examo-neg:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    container_name: examo-neg
    image: examo-neg:latest
    command: "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
#    env_file:
#      - .env

